package:
  name: progressivis
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: ../

requirements:
  build:
    - python 3.11
    - setuptools >=64
    - setuptools_scm >=8
    - cython >=0.26.1
    - numpy >=1.22.4

  host:
    - python 3.11
    - cython >=0.26.1
    - numpy >=1.22.4
    - scipy >=0.19.1
    - numexpr >=2.6.1
    - pandas >=1.2.5
    - pyarrow >=8.0.0
    - scikit-learn >=1.0.0
    - pyyaml >=5.4.1
    - pillow >=4.2.0
    - pyroaring
    - boto
    - s3fs
    - requests
    - fast-histogram >=0.11
    - rangehttpserver
    - datasketches
    - typeguard
    - multipledispatch >=0.4.7


  run:
    - python 3.11
    - numpy >=1.22.4
    - scipy >=0.19.1
    - numexpr >=2.6.1
    - pandas >=1.2.5
    - pyarrow >=8.0.0
    - scikit-learn >=1.0.0
    - pyyaml >=5.4.1
    - pillow >=4.2.0
    - pyroaring
    - boto
    - s3fs
    - requests
    - fast-histogram >=0.11
    - rangehttpserver
    - datasketches
    - typeguard
    - multipledispatch >=0.4.7
    - click

about:
  home: https://github.com/progressivis/progressivis
  license: New BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdfekete
    - xtianpoli
