repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      # Run the linter.
      - id: ruff
        exclude: notebooks

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.0
    hooks:
      - id: mypy
        language_version: python3.11
        exclude: ^progressivis/datashape/
        pass_filenames: false
        args: [--strict, --explicit-package-bases]
        additional_dependencies:
          - 'numpy'
          - 'ipython'
          - 'jinja2'
          - 'sqlalchemy-stubs'
          - 'pandas-stubs'
          - 'traits-stubs'
          - 'traittypes'
          - 'types-pillow'
          - 'types-pytz'
          - 'types-pyyaml'
          - 'types-requests'
          - 'types-urllib3'
          - 'typing-extensions'
          - 'typing_extensions'
          - 'types-setuptools'
          - 'typeguard'