repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/flake8
    rev: ''
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        exclude: ^stool/
        args: [--explicit-package-bases]
        additional_dependencies:
          - 'numpy'
          - 'ipython'
          - 'jinja2'
          - 'sqlalchemy-stubs'
          - 'pandas-stubs'
          - 'traits-stubs'
          - 'traittypes'
          - 'types-pillow'
          - 'types-pytz'
          - 'types-pyyaml'
          - 'types-requests'
          - 'types-urllib3'
          - 'typing-extensions'
          - 'typing_extensions'
          - 'types-setuptools'