name: progressivis

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.8
  - nodejs
  - pkgconfig
  - pip
  - numpy>=1.21.4
  - scipy>=0.18.1
  - numexpr>=2.6.1
  - pandas>=1.2.5
  - pillow>=4.2.0
  - pyyaml>=5.4.1
  - requests
  - scikit-learn>=1.0.0
  - cython
  - pybind11
  - xtensor-python
  - croaring=0.2.63
  - pyroaring==0.2.11
  - datashape
  - fast-histogram
  - python-engineio=3.13.2
  - python-socketio=4.6.0
  - s3fs
  - voila
  - jupyterlab=2
  - ipywidgets>=7.0.0
  - ipydatawidgets=4.0.1
  - aiohttp
  - aiohttp-jinja2
  - click
  - pandas-stubs
  - types-pillow
  - pip:
    - tdigest>=0.4.1.0
    - rangehttpserver
    - traits-stubs
    - -e .
    - -e ./widgets
