name: progressivis

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.8
  - nodejs
  - pkgconfig
  - pip
  - numpy>=1.16.5
  - scipy>=0.18.1
  - numexpr>=2.6.1
  - pandas>=1.0.0
  - pillow>=4.2.0
  - requests
  - scikit-learn>=0.18.1
  - cython
  - pybind11
  - xtensor-python
  - croaring=0.2.63
  - pyroaring==0.2.11
  - datashape
  - fast-histogram
  - python-socketio
  - s3fs
  - voila
  - jupyterlab=2
  - ipywidgets>=7.0.0
  - ipydatawidgets=4.0.1
  - aiohttp
  - aiohttp-jinja2
  - click
  - pip:
    - tdigest>=0.4.1.0
    - rangehttpserver
    - -e .
    - -e ./widgets
