from __future__ import annotations

import numpy as np

from typing import Any, Dict, Tuple, Type, Sequence, Union, List
from progressivis.core.types import Floats

class kll_floats_sketch:
    def __init__(self, val: float) -> None: ...
    def get_pmf(self, val: Floats) -> Floats: ...
    def update(self, val: float) -> None: ...
    def merge(self, val: kll_floats_sketch) -> None: ...
    def get_min_value(self) -> float: ...
    def get_max_value(self) -> float: ...
    def get_quantiles(self, v: Floats) ->Floats: ...
