
ATTR_TABLE = 'PROGRESSIVE_TABLE'
ATTR_NROWS = 'NROWS'
ATTR_TITLE = 'TITLE'
ATTR_DESCRIPTION = 'DESCRIPTION'
ATTR_DATASHAPE = 'PROGRESSIVE_DATASHAPE'
ATTR_VERSION = 'PROGRESSIVE_VERSION'
VALUE_VERSION = "0.0"
ATTR_COLUMN = 'PROGRESSIVE_COLUMN'
ATTR_DATASHAPE = 'PROGRESSIVE_DATASHAPE'

