name: Doc generation

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Install ProgressiVis + doc tools
      run: |
        python -m pip install -r doc/requirements_doc.txt
        python -m pip install .
    - name: Make html
      run: |
        pushd doc
        make html SPHINXOPTS="-W --keep-going -n"
        popd
    - name: Upload doc
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: progressivis-doc
        path: doc/_build/
