name: Python Tests on Windows

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        python: ["3.12"]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Download a file
      run: |
        # wget --no-verbose https://datahub.io/machine-learning/mnist_784/r/mnist_784.csv -O mnist_784.csv
        mkdir data
        # mv mnist_784.csv data/ # disabled cause mnist_784.csv is not longer available

    - name: Run tests
      run: |
        python -m pip install .[test]
        coverage run -m pytest tests -vv

    - name: Coverage
      run: |
        coverage html

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.python }}
        path: htmlcov

    - name: Pip freeze
      if: failure()
      run: |
        mkdir -p downloads/${{ matrix.python }}/
        python -m pip freeze > downloads/${{ matrix.python }}/pip_freeze.txt
    - name: Upload frozen env
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: pip-freeze
        path: downloads
